version: "3"
services:
  app:
    container_name: app
    build:
      context: ./containers/rails
    env_file:
      - ./containers/db/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./containers/rails:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
  db:
    container_name: db
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    env_file:
      - ./containers/db/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    container_name: web
    build:
      context: ./containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 8080:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
